server:
  port: 9090
  servlet:
    context-path: /file-storage/api/v1

spring:
  application:
    name: file-uploader-spring-boot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file_storage
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
